export interface GeoEvent {
  id: string
  title: string
  location: string
  lat: number
  lng: number
  severity: number
  sentiment: number
  source: string
  time: string
  category: string
  relatedChokepoint?: string
}

export const geoEvents: GeoEvent[] = [
  {
    id: 'e1',
    title: 'Houthi missile attack on commercial tanker in Red Sea',
    location: 'Red Sea, Yemen',
    lat: 15.0,
    lng: 42.0,
    severity: 0.92,
    sentiment: -0.85,
    source: 'GDELT',
    time: '15 min ago',
    category: 'Attack',
    relatedChokepoint: 'bab-el-mandeb',
  },
  {
    id: 'e2',
    title: 'Iran naval exercises near Strait of Hormuz',
    location: 'Strait of Hormuz',
    lat: 26.5,
    lng: 56.5,
    severity: 0.75,
    sentiment: -0.60,
    source: 'GDELT',
    time: '1h ago',
    category: 'Military',
    relatedChokepoint: 'hormuz',
  },
  {
    id: 'e3',
    title: 'US announces new sanctions on Venezuelan oil exports',
    location: 'Washington DC',
    lat: 38.9,
    lng: -77.0,
    severity: 0.68,
    sentiment: -0.55,
    source: 'GDELT',
    time: '2h ago',
    category: 'Sanctions',
  },
  {
    id: 'e4',
    title: 'Fire at ExxonMobil Baytown refinery disrupts operations',
    location: 'Baytown, TX',
    lat: 29.75,
    lng: -95.01,
    severity: 0.60,
    sentiment: -0.40,
    source: 'GDELT',
    time: '3h ago',
    category: 'Refinery',
  },
  {
    id: 'e5',
    title: 'OPEC+ ministerial meeting concludes with production quota agreement',
    location: 'Vienna, Austria',
    lat: 48.2,
    lng: 16.4,
    severity: 0.82,
    sentiment: -0.30,
    source: 'GDELT',
    time: '4h ago',
    category: 'OPEC',
  },
  {
    id: 'e6',
    title: 'Pipeline explosion in Nigeria disrupts Bonny Light exports',
    location: 'Niger Delta, Nigeria',
    lat: 4.8,
    lng: 6.8,
    severity: 0.72,
    sentiment: -0.70,
    source: 'GDELT',
    time: '5h ago',
    category: 'Infrastructure',
  },
  {
    id: 'e7',
    title: 'Russian oil depot hit by drone strike in Bryansk region',
    location: 'Bryansk, Russia',
    lat: 53.2,
    lng: 34.4,
    severity: 0.78,
    sentiment: -0.65,
    source: 'GDELT',
    time: '6h ago',
    category: 'Attack',
  },
  {
    id: 'e8',
    title: 'Libya\'s NOC declares force majeure on Sharara crude',
    location: 'Sharara, Libya',
    lat: 28.5,
    lng: 12.2,
    severity: 0.70,
    sentiment: -0.58,
    source: 'GDELT',
    time: '8h ago',
    category: 'Supply',
  },
  {
    id: 'e9',
    title: 'EU approves 14th sanctions package targeting Russian oil revenue',
    location: 'Brussels, Belgium',
    lat: 50.8,
    lng: 4.4,
    severity: 0.65,
    sentiment: -0.42,
    source: 'GDELT',
    time: '10h ago',
    category: 'Sanctions',
  },
  {
    id: 'e10',
    title: 'Typhoon warning issued for South China Sea shipping lanes',
    location: 'South China Sea',
    lat: 15.0,
    lng: 115.0,
    severity: 0.55,
    sentiment: -0.35,
    source: 'GDELT',
    time: '12h ago',
    category: 'Weather',
  },
  {
    id: 'e11',
    title: 'Iraq announces plans to increase oil output to 6M bbl/d by 2028',
    location: 'Baghdad, Iraq',
    lat: 33.3,
    lng: 44.4,
    severity: 0.40,
    sentiment: 0.30,
    source: 'GDELT',
    time: '14h ago',
    category: 'Production',
  },
  {
    id: 'e12',
    title: 'Turkish straits congestion increases amid seasonal demand',
    location: 'Istanbul, Turkey',
    lat: 41.1,
    lng: 29.0,
    severity: 0.35,
    sentiment: -0.15,
    source: 'GDELT',
    time: '16h ago',
    category: 'Shipping',
    relatedChokepoint: 'bosporus',
  },
]
