export interface OilField {
  id: string
  name: string
  country: string
  region: string
  production: number
  reserves: number
  breakeven: number
  rpRatio: number
  yearDiscovered: number
  peakYear: number
  waterCut: number
  apiGravity: number
  status: 'producing' | 'mature' | 'declining'
}

export const oilFields: OilField[] = [
  {
    id: 'ghawar',
    name: 'Ghawar',
    country: 'Saudi Arabia',
    region: 'Middle East',
    production: 3800,
    reserves: 75000,
    breakeven: 10,
    rpRatio: 19.7,
    yearDiscovered: 1948,
    peakYear: 1981,
    waterCut: 0.45,
    apiGravity: 34,
    status: 'mature',
  },
  {
    id: 'burgan',
    name: 'Burgan',
    country: 'Kuwait',
    region: 'Middle East',
    production: 1600,
    reserves: 66000,
    breakeven: 8.5,
    rpRatio: 41.3,
    yearDiscovered: 1938,
    peakYear: 1972,
    waterCut: 0.30,
    apiGravity: 32,
    status: 'mature',
  },
  {
    id: 'cantarell',
    name: 'Cantarell',
    country: 'Mexico',
    region: 'Americas',
    production: 430,
    reserves: 8500,
    breakeven: 25,
    rpRatio: 19.8,
    yearDiscovered: 1976,
    peakYear: 2004,
    waterCut: 0.72,
    apiGravity: 22,
    status: 'declining',
  },
  {
    id: 'permian',
    name: 'Permian Basin',
    country: 'United States',
    region: 'Americas',
    production: 6200,
    reserves: 48000,
    breakeven: 48,
    rpRatio: 7.7,
    yearDiscovered: 1921,
    peakYear: 2024,
    waterCut: 0.15,
    apiGravity: 38,
    status: 'producing',
  },
  {
    id: 'brent',
    name: 'Brent (North Sea)',
    country: 'United Kingdom',
    region: 'Europe',
    production: 120,
    reserves: 800,
    breakeven: 52,
    rpRatio: 6.7,
    yearDiscovered: 1971,
    peakYear: 1999,
    waterCut: 0.55,
    apiGravity: 38,
    status: 'declining',
  },
  {
    id: 'kashagan',
    name: 'Kashagan',
    country: 'Kazakhstan',
    region: 'Central Asia',
    production: 900,
    reserves: 30000,
    breakeven: 35,
    rpRatio: 33.3,
    yearDiscovered: 2000,
    peakYear: 2025,
    waterCut: 0.10,
    apiGravity: 44,
    status: 'producing',
  },
  {
    id: 'orinoco',
    name: 'Orinoco Belt',
    country: 'Venezuela',
    region: 'Americas',
    production: 750,
    reserves: 303000,
    breakeven: 22,
    rpRatio: 404,
    yearDiscovered: 1935,
    peakYear: 2008,
    waterCut: 0.08,
    apiGravity: 8,
    status: 'mature',
  },
  {
    id: 'tengiz',
    name: 'Tengiz',
    country: 'Kazakhstan',
    region: 'Central Asia',
    production: 680,
    reserves: 26000,
    breakeven: 30,
    rpRatio: 38.2,
    yearDiscovered: 1979,
    peakYear: 2023,
    waterCut: 0.20,
    apiGravity: 46,
    status: 'producing',
  },
]
